# version: "3.8"

services:
  postgre:
  #  container_name: postgresql
    image: postgres:12.17
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: Pg123
      POSTGRES_USER: kubenews
      POSTGRES_DB: kubenews
    volumes:
    #  - C:\Users\lucas\Documents\DevopsPro\kubenews\kube-news\db_volume:/var/lib/postgresql/data
      - postgre_voldb:/var/#lib/postgresql/data
    networks:
      - kubenews_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kubenews"]
      interval: 5s
      timeout: 5s
      retries: 5


  kubenews:
   # container_name: kube-web
    image: lufertony/kube-news
    depends_on:
      postgre:
        condition: service_healthy

    build:
      context: ./src
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    networks:
      - kubenews_net

    environment:
      DB_PASSWORD: Pg123
      DB_USERNAME: kubenews
      DB_DATABASE: kubenews
      DB_HOST: postgre


volumes:
  postgre_voldb:
    name: meu_postgre_voldb
  #  external: true

networks:
  kubenews_net:
    driver: bridge
    name: kubenews_net