# version: "3.8"

services:
  postgre:
    container_name: postgresql
    image: postgres:12.17
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: Pg123
      POSTGRES_USER: kubenews
      POSTGRES_DB: kubenews
    volumes:
    #  - C:\Users\lucas\Documents\DevopsPro\kubenews\kube-news\db_volume:/var/lib/postgresql/data
      - postgre_voldb:/var/#lib/postgresql/data
    networks:
      - kubenews_net

  kubenews:
    container_name: kube-web
    image: lufertony/kube-news:v1
    ports:
      - 8080:8080
    networks:
      - kubenews_net
    environment:
      DB_PASSWORD: Pg123
      DB_USERNAME: kubenews
      DB_DATABASE: kubenews
      DB_HOST: postgresql


volumes:
  postgre_voldb:
    name: meu_postgre_voldb
  #  external: true

networks:
  kubenews_net:
    driver: bridge
    name: kubenews_net