# version: "3.8"

services:
  postgre:
  #  container_name: postgresql
    image: postgres:12.17
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${PG_PASS}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_DB: ${PG_DB}
    volumes:
    #  - C:\Users\lucas\Documents\DevopsPro\kubenews\kube-news\db_volume:/var/lib/postgresql/data
      - postgre_voldb:/var/#lib/postgresql/data
    networks:
      - kubenews_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kubenews"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    extends:
      file: ./kn-compose.yaml
      service: kubenews
    image: lufertony/web-news:latest
    profiles:
      - dev
      - hml

volumes:
  postgre_voldb:
    name: meu_postgre_voldb
  #  external: true

networks:
  kubenews_net:
    driver: bridge
    name: kubenews_net