# version: "3.8"

services:
  postgre:
    container_name: postgresql
    image: postgres:12.17
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: Pg123
      POSTGRES_USER: kubenews
      POSTGRES_DB: kubenews
    volumes:
    #  - C:\Users\lucas\Documents\DevopsPro\kubenews\kube-news\db_volume:/var/lib/postgresql/data
      - postgre_voldb:/var/#lib/postgresql/data

volumes:
  postgre_voldb:
    name: meu_postgre_voldb
  #  external: true

networks:
  kubenews_net:
    driver: bridge